# catch-all redirect
server {
    listen 443 ssl;
    server_name ~^(?:[\w-]+\.)+nanpa\.la$;

    # redirect
    location / { return https://ijo.tan.anpa.nanpa.la$request_uri; }
}

# primary server
server {
    listen 443 ssl;
    server_name nanpa.la;

    ### host static content ###
    # stylesheets
    location /ijo/nasin.css {
        alias /var/www/nanpa-la/css/nasin.css;
        add_header Content-Type text/css;
        
    }

    # fonts
    location /ijo/nasin-nanpa.otf {
        alias /var/www/nanpa-la/font/nasin-nanpa-5.0.0-beta.2.otf;
        add_header Content-Type font/otf;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    # snippets
    location /ijo/head.html {
        alias /var/www/nanpa-la/html/kipisi/head.html;
        add_header Content-Type text/html;
    }

    location /ijo/ante-toki.html {
        alias /var/www/nanpa-la/html/kipisi/ante-toki.html;
        add_header Content-Type text/html;
    }

    # scripts
    location /ijo/ante-toki.js {
        alias /var/www/nanpa-la/js/ante-toki.js;
        add_header Content-Type text/javascript;
    }

    # images
    location /ijo/favicon.ico {
        alias /var/www/nanpa-la/img/favicon.ico;
        add_header Content-Type image/x-icon;
    }

    location /ijo/language-icon.svg {
        alias /var/www/nanpa-la/img/language-icon.svg;
        add_header Content-Type image/svg+xml;
    }

    location /ijo/ale-li-pona.gif {
        alias /var/www/nanpa-la/img/ale-li-pona.gif;
        add_header Content-Type image/gif;
    }

    location /ijo/itan.png {
        alias /var/www/nanpa-la/img/itan.png;
        add_header Content-Type image/png;
    }

    # redirect
    location / { return https://ijo.tan.anpa.nanpa.la$request_uri; }
}

# home page
server {
    listen 443 ssl;
    server_name ijo.tan.anpa.nanpa.la;

    location / {
        root /var/www/nanpa-la/html/itan;
        include /var/www/nanpa-la/nasin/pana.conf;
    }
}

# redirect to nasitan's page
server {
    listen 443 ssl;
    server_name
        nasin.nanpa.la
        .sitelen.tan.anpa.nanpa.la
    ;

    location /ijo/ { proxy_pass https://nanpa.la; }
    location / { return https://nasin.sitelen.tan.anpa.nanpa.la$request_uri; }
}

# nasitan's page
server {
    listen 443 ssl;
    server_name nasin.sitelen.tan.anpa.nanpa.la;

    location / {
        root /var/www/nanpa-la/html/nasitan;
        include /var/www/nanpa-la/nasin/pana.conf;
    }
}

# redirect to music page
server {
    listen 443 ssl;
    server_name
        mu.nanpa.la
        kalama.nanpa.la
    ;

    location / { return https://kalama.tan.anpa.nanpa.la$request_uri; }
}

# music page
server {
    listen 443 ssl;
    server_name kalama.tan.anpa.nanpa.la;
    location / { return https://ijotananpananpa.bandcamp.com/; }
}


# redirect to writings page
server {
    listen 443 ssl;
    server_name lipu.nanpa.la;

    location /ijo/ { proxy_pass https://nanpa.la; }
    location / { return https://lipu.tan.anpa.nanpa.la$request_uri; }
}

# writings page
server {
    listen 443 ssl;
    server_name lipu.tan.anpa.nanpa.la;

    location / {
        root /var/www/nanpa-la/html/lipu;
        include /var/www/nanpa-la/nasin/pana.conf;
    }
}

