location /ijo/ { proxy_pass https://nanpa.la; }

# set $toki "sp";

# if ($http_cookie ~* "toki=tp") { set $toki "tp"; }
# if ($http_cookie ~* "toki=en") { set $toki "en"; }

# index ${toki}.html sp.html tp.html en.html;

try_files $uri $uri/ =404;
