# catch-all redirect
server {
    listen 443 ssl;
    server_name ~^(?:[\w-]+\.)+nanpa\.la$;

    # redirect
    location / { return https://ijo.tan.anpa.nanpa.la$request_uri; }
}

# primary server
server {
    listen 443 ssl;
    server_name nanpa.la;

    # host static content
    location /ijo/nasin.css {
        alias /var/www/nanpa-la/css/nasin.css;
        add_header Content-Type text/css;
    }

    location /ijo/nasin-nanpa.otf {
        alias /var/www/nanpa-la/font/nasin-nanpa-5.0.0-beta.2.otf;
        add_header Content-Type font/otf;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location /ijo/head.html {
        alias /var/www/nanpa-la/html/kipisi/head.html;
        add_header Content-Type text/html;
    }

    location /ijo/suli.js {
        alias /var/www/nanpa-la/js/suli.js;
        add_header Content-Type text/javascript;
    }

    # redirect
    location / { return https://ijo.tan.anpa.nanpa.la$request_uri; }
}

# home page
server {
    listen 443 ssl;
    server_name ijo.tan.anpa.nanpa.la;

    location /ijo/ { proxy_pass https://nanpa.la; }

    location / {
        root /var/www/nanpa-la/html/itan;
        try_files $uri $uri/ =404;
    }
}

# redirect to nasitan's page
server {
    listen 443 ssl;
    server_name
        nasin.nanpa.la
        .sitelen.tan.anpa.nanpa.la
    ;

    location /ijo/ { proxy_pass https://nanpa.la; }
    location / { return https://nasin.sitelen.tan.anpa.nanpa.la$request_uri; }
}

# nasitan's page
server {
    listen 443 ssl;
    server_name nasin.sitelen.tan.anpa.nanpa.la;

    location /ijo/ { proxy_pass https://nanpa.la; }

    location / {
        root /var/www/nanpa-la/html/nasitan;
        try_files $uri $uri/ =404;
    }
}

# redirect to music page
server {
    listen 443 ssl;
    server_name
        mu.nanpa.la
        kalama.nanpa.la
    ;

    location /ijo/ { proxy_pass https://nanpa.la; }
    location / { return https://kalama.tan.anpa.nanpa.la$request_uri; }
}

# music page
server {
    listen 443 ssl;
    server_name kalama.tan.anpa.nanpa.la;

    # location / {
    #     root /var/www/nanpa-la/html/kalama;
    #     try_files $uri $uri/ =404;
    # }

    location /ijo/ { proxy_pass https://nanpa.la; }

    location / { return https://ijotananpananpa.bandcamp.com/; }
}


# redirect to writings page
server {
    listen 443 ssl;
    server_name lipu.nanpa.la;

    location /ijo/ { proxy_pass https://nanpa.la; }
    location / { return https://lipu.tan.anpa.nanpa.la$request_uri; }
}

# writings page
server {
    listen 443 ssl;
    server_name lipu.tan.anpa.nanpa.la;

    location /ijo/ { proxy_pass https://nanpa.la; }

    location / {
        root /var/www/nanpa-la/html/lipu;
        try_files $uri $uri/ =404;
    }
}

