# http block (redirect to https)
server {
    server_name nanpa.la ~^(?:[\w-]+\.)+nanpa\.la$;
    listen 80;      # IPv4
    listen [::]:80; # IPv6

    # http -> https
    location / { return 301 https://$server_name$request_uri; }
}

